Style/EndOfLine:
  Enabled: false

Style/SignalException:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - '**/*_spec.rb'
    - '**/ruby_on_rays.gemspec'


Metrics/ModuleLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/AbcSize:
  Max: 25 # Default is 15.
